(() => {
'use strict';
const palette = [
 ['Ocean','#07669e','#08436d','#06283f','Main supporting colour · modern biofuels in 8A'],
 ['Mint','#04ffba','#079b79','#064a3e','Main highlight colour · solar, wind and other renewables in 8A'],
 ['Coral','#d45463','#913142','#451322','Coal'],
 ['Orchid','#a51b91','#691b70','#2e103e','Oil'],
 ['Magenta','#e30063','#9b0847','#490c2c','Gas'],
 ['Forest','#0f875f','#08553f','#043128','Hydro'],
 ['Gold orange','#ffb21c','#bc6412','#652508','Secondary accent · traditional wood and biomass in 8A']
];
const NS='http://www.w3.org/2000/svg';
function el(tag, attrs={}, parent){const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);if(parent)parent.append(n);return n;}
function text(g,x,y,s,attrs={}){const n=el('text',{x,y,...attrs},g);n.textContent=s;return n;}
let serial=0;
function base(host,title){
 const root=el('svg',{viewBox:'0 0 800 500',role:'img','aria-label':title+' — illustrative sample data'},host);
 const defs=el('defs',{},root),prefix='s'+(++serial);
 palette.forEach((p,i)=>{const g=el('linearGradient',{id:prefix+'g'+i,x1:0,y1:0,x2:0,y2:1},defs);[0,.55,1].forEach((v,j)=>el('stop',{offset:v,'stop-color':p[j+1],'stop-opacity':[.88,.78,.68][j]},g));});
 const glow=el('filter',{id:prefix+'glow',x:'-25%',y:'-25%',width:'150%',height:'150%'},defs);el('feDropShadow',{dx:0,dy:0,stdDeviation:1.8,'flood-color':'#04ffba','flood-opacity':.25},glow);
 const bg=el('linearGradient',{id:prefix+'bg',x1:0,y1:0,x2:1,y2:1},defs);el('stop',{offset:0,'stop-color':'#102a43'},bg);el('stop',{offset:1,'stop-color':'#010b12'},bg);
 el('rect',{width:800,height:500,fill:`url(#${prefix}bg)`},root);
 for(let i=0;i<3;i++)el('path',{d:`M0 ${438+i*25} Q230 ${380+i*23} 440 ${440+i*14} T800 ${420+i*20}`,fill:'none',stroke:'#326887','stroke-opacity':.2},root);
 text(root,45,52,title,{'font-size':26,'font-weight':700,fill:'#f8fbff'});
 text(root,755,478,'Illustrative data · Style reference',{'font-size':13,'text-anchor':'end',fill:'#a9c2d6'});
 return {root,defs,prefix};
}
function axes(c,{max=100,labels=['2000','2005','2010','2015','2020','2025'],unit='Index'}={}){
 const g=c.root;
 for(let i=0;i<=4;i++){const y=420-i*76;el('line',{x1:85,x2:755,y1:y,y2:y,stroke:'#a9c2d6','stroke-opacity':i?.16:.4},g);text(g,72,y+6,String(Math.round(max*i/4)),{'text-anchor':'end'});}
 labels.forEach((s,i)=>text(g,85+i*670/(labels.length-1||1),445,s,{'text-anchor':'middle'}));
 text(g,85,92,unit,{'font-size':15});
}
function line(c,d,color=1,width=3,attrs={}){return el('path',{d,fill:'none',stroke:palette[color][1],'stroke-width':width,'stroke-linejoin':'round','stroke-linecap':'round',...attrs},c.root);}
function fill(c,d,color=0,{texture=true,edge=true}={}){
 const id=c.prefix+'clip'+(++serial);el('path',{d,fill:`url(#${c.prefix}g${color})`},c.root);
 const clip=el('clipPath',{id},c.defs);el('path',{d},clip);
 const group=el('g',{'clip-path':`url(#${id})`,'aria-hidden':'true'},c.root);
 if(texture){const waves=el('g',{class:'texture'},group);for(let i=0;i<24;i++){let path='';for(let x=70;x<=770;x+=10){const y=125+i*13+Math.sin(x/95+i*.21)*12+Math.sin(x/173+i*.7)*9;path+=(x===70?'M':'L')+x+' '+y.toFixed(2)+' ';}el('path',{d:path,fill:'none',stroke:'#fff','stroke-width':.7,'stroke-opacity':.1+(i%3)*.02},waves);}}
 el('path',{d,fill:'none',stroke:'#01060c','stroke-width':7,'stroke-opacity':.35,transform:'translate(0 3)',class:'edge-shadow'},group);
 if(edge)line(c,d,color,1.4);
}
function dot(c,x,y,color=1,r=5){el('circle',{cx:x,cy:y,r,fill:palette[color][1],stroke:'#f8fbff','stroke-width':1,'stroke-opacity':.7},c.root);}
function bar(c,x,y,w,h,color=0){fill(c,`M${x} ${y+h}V${y}h${w}v${h}Z`,color);}
function legend(c,items){let x=85;items.forEach(([label,col])=>{el('rect',{x,y:67,width:10,height:10,rx:2,fill:palette[col][1]},c.root);text(c.root,x+16,77,label,{'font-size':14});x+=label.length*7+45;});}
const pts=vals=>vals.map((v,i)=>[85+i*670/(vals.length-1),420-v*3.04]);
const path=points=>points.map(([x,y],i)=>(i?'L':'M')+x+','+y).join(' ');
function curve(c,vals,col=0,area=false){const p=pts(vals),d=path(p);if(area)fill(c,d+' L755 420 L85 420 Z',col,{edge:false});if(area)line(c,d,col,6,{'stroke':'#01060c','stroke-opacity':.3,transform:'translate(0 3)',class:'edge-shadow'});line(c,d,col,2.6);return p;}
const examples=[
 ['Area','Time & trends','Growth with weight','A single quantity through time. The fill makes magnitude visible while the bright upper edge carries the exact shape.','Mint','Trace left to right; anchor the gradient to the highest revealed value. Hold for one second at narration breaks.',c=>{axes(c);curve(c,[12,15,18,24,38,43,61,85],1,true);dot(c,755,161.6,1);}],
 ['Stacked area','Time & trends','How a total accumulates','The closest relative of 8A. Give each band its own dark accent, thin edge and clipped waves. Keep category order consistent.','Ocean · Orchid · Mint','Reveal all bands together through time; expand axes only at explicit era boundaries.',c=>{axes(c);legend(c,[['Base',0],['Added',3],['Newest',1]]);const a=[12,15,18,20,22,24],b=[12,17,24,33,46,60],d=[12,17,25,39,64,89];[a,b,d].forEach((vs,i)=>{const p=pts(vs),lower=i?pts([a,b][i-1]).reverse():[[755,420],[85,420]];fill(c,path(p)+' '+lower.map(v=>'L'+v.join(',')).join(' ')+' Z',[0,3,1][i]);});}],
 ['Line','Time & trends','The change is the story','Use a crisp mint stroke with restrained glow and an endpoint marker. Keep the plot open when area is not meaningful.','Mint','Draw the actual path; reveal markers when the line reaches them.',c=>{axes(c);const vs=[20,42,35,63,53,70,62,88];const p=curve(c,vs,1);c.root.lastElementChild.setAttribute('filter',`url(#${c.prefix}glow)`);p.forEach(([x,y])=>dot(c,x,y,1,4));}],
 ['Multiple lines','Time & trends','Compare trajectories','Use distinct colours and dash patterns, plus direct labels. Avoid several overlapping gradient fills.','Ocean · Mint · Coral','Introduce series in voiceover order, then hold the complete comparison.',c=>{axes(c);legend(c,[['Series A',0],['Series B',1],['Series C',2]]);curve(c,[10,20,28,45,60,90],0);line(c,path(pts([25,28,36,41,52,68])),1,3,{'stroke-dasharray':'9 6'});line(c,path(pts([50,43,45,34,30,22])),2,3,{'stroke-dasharray':'2 7'});}],
 ['Uncertainty band','Time & trends','Show the range honestly','Use a faint band behind a solid central estimate. Decorative waves stay off here so they cannot be confused with observations.','Mint','Reveal the band with the estimate; label the interval and distinguish forecasts from observations.',c=>{axes(c);legend(c,[['Estimate + uncertainty interval',1]]);const bandStart=c.root.children.length;fill(c,path(pts([22,33,47,63,81,96]))+' '+pts([15,19,27,31,37,45]).reverse().map(p=>'L'+p.join(',')).join(' ')+'Z',1,{texture:false,edge:false});Array.from(c.root.children).slice(bandStart).forEach(n=>n.setAttribute('opacity',.3));line(c,path(pts([18,26,37,47,59,71])),1);}],
 ['Column','Comparison','Compare discrete amounts','Use square-ended bars, bright caps and individual gradients. Start the value axis at zero; keep category gaps even.','Ocean · Mint highlight','Grow each bar from the baseline in sequence; introduce the highlight after the comparison.',c=>{axes(c,{labels:[]});[42,65,51,87,70,57].forEach((v,i)=>{bar(c,110+i*108,420-v*3.04,55,v*3.04,i===3?1:0);text(c.root,137+i*108,445,'ABCDEF'[i],{'text-anchor':'middle'});text(c.root,137+i*108,410-v*3.04,v,{'text-anchor':'middle'});});}],
 ['Horizontal bar','Comparison','Rank long labels','Leave room for labels, use equal bar thickness and put values just beyond the ends. Fade colour downward within each bar.','Ocean · Mint emphasis','Reveal top to bottom. Highlight a narrated category after the ranking settles.',c=>{['Education','Health','Employment','Infrastructure','Environment'].forEach((n,i)=>{const y=122+i*57,v=[91,78,63,48,24][i];text(c.root,190,y+23,n,{'text-anchor':'end'});bar(c,210,y,v*5.4,32,i===4?1:0);text(c.root,222+v*5.4,y+23,v);});}],
 ['Grouped bar','Comparison','Side-by-side categories','Use consistent left/right order and a shared baseline. Give related bars matching widths and avoid unnecessary outlines on all four sides.','Ocean · Mint','Reveal each pair together so the comparison is immediately readable.',c=>{axes(c,{labels:[]});legend(c,[['Earlier',0],['Later',1]]);[0,1,2,3].forEach(i=>{[35+i*9,47+i*12].forEach((v,j)=>bar(c,130+i*155+j*42,420-v*3.04,34,v*3.04,j));text(c.root,168+i*155,445,'Group '+(i+1),{'text-anchor':'middle'});});}],
 ['Stacked bar','Composition','Parts of a total','Apply a separate gradient to every segment. Thin boundaries keep the dark bases from merging; use a stable legend order.','Ocean · Orchid · Mint','Build the base category first, then add each layer without shifting the baseline.',c=>{axes(c,{labels:[]});legend(c,[['Base',0],['Middle',3],['Top',1]]);[0,1,2,3,4].forEach(i=>{let y=420;[24+i*3,15+i*2,12+i*3].forEach((v,j)=>{const h=v*3.04;y-=h;bar(c,120+i*125,y,65,h,[0,3,1][j]);});text(c.root,152+i*125,445,'ABCDE'[i],{'text-anchor':'middle'});});}],
 ['Diverging bar','Comparison','Above and below a reference','Make the zero line unmistakable. Put labels outside each end, and use colour plus position to distinguish direction.','Ocean · Mint','Extend bars outward from zero. Never animate through values that change the sign.',c=>{el('line',{x1:415,x2:415,y1:105,y2:425,stroke:'#eef3fa','stroke-opacity':.6},c.root);text(c.root,415,447,'0',{'text-anchor':'middle'});[-65,-32,24,47,78].forEach((v,i)=>{const y=115+i*60;bar(c,v<0?415+v*4:415,y,Math.abs(v)*4,32,v<0?0:1);text(c.root,v<0?403+v*4:427+v*4,y+23,(v>0?'+':'')+v,{'text-anchor':v<0?'end':'start'});});}],
 ['Waterfall','Comparison','Explain a net change','Floating bars connect successive totals. Use neutral dotted connectors; reserve a full baseline bar for the start and finish.','Ocean · Mint · Coral','Introduce each change, update the running total, then reveal the final total.',c=>{axes(c,{labels:[]});let total=35;[35,22,-12,30,75].forEach((v,i)=>{const isTotal=i===0||i===4,start=isTotal?0:total,end=isTotal?v:total+v,x=105+i*132;bar(c,x,420-Math.max(start,end)*3.04,65,Math.abs(end-start)*3.04,isTotal?0:v>0?1:2);if(i<4)el('line',{x1:x+65,x2:x+132,y1:420-end*3.04,y2:420-end*3.04,stroke:'#a9c2d6','stroke-dasharray':'3 5'},c.root);text(c.root,x+32,445,['Start','Gain','Loss','Gain','End'][i],{'text-anchor':'middle'});total=end;});}],
 ['Scatter','Relationships','Individual observations','Small solid points use bright outlines and minimal glow. Label selected observations; keep texture in large callouts, not behind every point.','Ocean · Mint focus','Populate points in a deliberate order; bring in interpretation only after the observations.',c=>{axes(c,{labels:['0','20','40','60','80','100'],unit:'Outcome'});for(let i=0;i<34;i++){const x=110+i*18,y=400-i*6.6+Math.sin(i*2.1)*41;dot(c,x,y,i===25?1:0,i===25?8:4);}text(c.root,584,183,'Selected observation',{'font-size':15});}],
 ['Bubble','Relationships','Add a third quantity','Scale circle area, not radius, to the third variable. Use translucent gradients and thin outlines; label sizes explicitly.','Ocean · Mint · Orchid','Place centres first, then grow bubbles to their correct area without an overshoot.',c=>{axes(c,{labels:['0','20','40','60','80','100'],unit:'Outcome · bubble area = quantity'});[[160,350,18,0],[260,300,25,1],[350,340,14,3],[440,205,37,0],[550,260,27,1],[665,150,45,3]].forEach(([x,y,r,col])=>{el('circle',{cx:x,cy:y,r,fill:`url(#${c.prefix}g${col})`,stroke:palette[col][1],'stroke-width':1.5},c.root);text(c.root,x,y+5,String(Math.round(r*r/10)),{'text-anchor':'middle','font-size':14,fill:'#fff'});});}],
 ['Dumbbell','Comparison','Before and after','Connect two observations with a quiet line. Make endpoint colours and labels explicit; the connector shows distance, not intermediate measurements.','Ocean · Mint','Reveal the first point, extend the connector, then reveal the second point.',c=>{legend(c,[['Before',0],['After',1]]);['A','B','C','D','E'].forEach((s,i)=>{const y=130+i*58,a=180+i*22,b=410+i*57;text(c.root,85,y+5,s);el('line',{x1:a,x2:b,y1:y,y2:y,stroke:'#a9c2d6','stroke-opacity':.45,'stroke-width':2},c.root);dot(c,a,y,0,7);dot(c,b,y,1,7);});}],
 ['Histogram','Distribution','Show the shape of a population','Touching bars represent equal-width bins. Use one hue so the silhouette carries the distribution; waves stay very subtle.','Ocean','Reveal bins left to right while keeping their widths and boundaries fixed.',c=>{axes(c,{labels:['0','20','40','60','80','100'],unit:'Frequency'});[10,24,48,72,91,83,65,40,20,8].forEach((v,i)=>bar(c,85+i*67,420-v*3.04,67,v*3.04,0));}],
 ['Box plot','Distribution','Compare spread and median','Use gradients inside the interquartile boxes only. White medians and thin whiskers must remain stronger than texture. Dots mark outliers.','Mint','Reveal whiskers, boxes, then medians and outliers; explain the whisker convention in the source note.',c=>{axes(c,{labels:[],unit:'Value · whiskers within 1.5 × IQR'});[0,1,2,3].forEach(i=>{const x=175+i*160,top=160+i*20,bottom=320-i*10;el('line',{x1:x,x2:x,y1:top-45,y2:bottom+38,stroke:'#a9c2d6','stroke-width':2},c.root);[top-45,bottom+38].forEach(y=>el('line',{x1:x-17,x2:x+17,y1:y,y2:y,stroke:'#a9c2d6','stroke-width':2},c.root));bar(c,x-34,top,68,bottom-top,1);el('line',{x1:x-34,x2:x+34,y1:(top+bottom)/2,y2:(top+bottom)/2,stroke:'#fff','stroke-width':3},c.root);dot(c,x,top-65,1,3);text(c.root,x,445,'ABCD'[i],{'text-anchor':'middle'});});}],
 ['Donut','Composition','A few parts of one whole','Keep category count small and include percentages. Use bright rim strokes and dark accented fills; a bar is better for close comparisons.','Ocean · Mint · Orchid','Reveal sectors clockwise from twelve o’clock, then settle labels and the centre total.',c=>{const vals=[50,30,20],cols=[0,1,3];let a=-Math.PI/2;vals.forEach((v,i)=>{const b=a+v/100*Math.PI*2,polar=(r,t)=>[310+Math.cos(t)*r,270+Math.sin(t)*r].join(',');const d=`M${polar(143,a)} A143 143 0 ${v>50?1:0} 1 ${polar(143,b)} L${polar(85,b)} A85 85 0 ${v>50?1:0} 0 ${polar(85,a)} Z`;fill(c,d,cols[i]);text(c.root,535,220+i*48,['A  50%','B  30%','C  20%'][i],{fill:palette[cols[i]][1],'font-size':24});a=b;});text(c.root,310,276,'100%',{'font-size':45,'font-weight':700,'text-anchor':'middle',fill:'#f8fbff'});}],
 ['Heatmap','Distribution','Find patterns in a matrix','Colour intensity encodes value, so use a single sequential scale and no decorative per-cell gradient. Keep 8A’s frame, type and restrained edges.','Mint intensity scale','Reveal rows or columns in reading order. Always show a numeric colour key.',c=>{for(let r=0;r<5;r++){text(c.root,100,143+r*49,'ABCDE'[r]);for(let k=0;k<10;k++){const v=(r*3+k*7)%11;el('rect',{x:130+k*58,y:117+r*49,width:54,height:43,fill:palette[1][1],'fill-opacity':.08+v*.084,stroke:'#04ffba','stroke-opacity':.15},c.root);}}text(c.root,130,405,'Low · 0');for(let i=0;i<10;i++)el('rect',{x:230+i*28,y:390,width:28,height:16,fill:'#04ffba','fill-opacity':.08+i*.093},c.root);text(c.root,530,405,'100 · High');}],
 ['Treemap','Composition','Nested parts of a whole','Rectangle area represents share. Use gradients within each region, thin boundaries and direct labels. Avoid this for precise ranking.','Ocean · Mint · Orchid · Coral','Reveal parent groups first, then their children; keep final areas fixed during comparison.',c=>{[[85,120,335,285,0,'A · 50%'],[428,120,327,140,1,'B · 25%'],[428,268,160,137,3,'C · 12.5%'],[596,268,159,137,2,'D · 12.5%']].forEach(([x,y,w,h,col,s])=>{bar(c,x,y,w,h,col);text(c.root,x+w/2,y+h/2+7,s,{'text-anchor':'middle',fill:'#fff','font-size':23,'font-weight':600});});}],
 ['Callout circle','Annotation','Circle the conclusion','Use a true circle with mint-to-deep-teal fill, clipped waves and an inner rim shadow. Keep the headline number large and the text centred.','Mint · White','Draw the outline first in about 0.8 seconds, then fill, then text. Hold the final state still.',c=>{const d='M540 270 A140 140 0 1 1 260 270 A140 140 0 1 1 540 270Z';fill(c,d,1);text(c.root,400,254,'0',{'font-size':88,'font-weight':700,fill:'#fff','text-anchor':'middle'});['Low energy,','high income','countries'].forEach((s,i)=>text(c.root,400,293+i*25,s,{'font-size':24,'font-weight':600,fill:'#fff','text-anchor':'middle'}));}]
];
const swatches=document.getElementById('swatches');
[palette[1],palette[0],palette[6],...palette.slice(2,6)].forEach(([name,bright,mid,dark,use])=>{const div=document.createElement('article');div.className='swatch';div.innerHTML=`<div class="colour-strip" style="background:linear-gradient(120deg,${bright},${mid} 55%,${dark})"></div><h3>${name}</h3><p>${use}</p><code>${bright.toUpperCase()} → ${mid.toUpperCase()} → ${dark.toUpperCase()}</code>`;swatches.append(div);});
const grid=document.getElementById('examples');
examples.forEach(([name,family,sub,desc,colors,motion,draw])=>{const article=document.createElement('article');article.className='example';article.dataset.family=family;article.id=name.toLowerCase().replaceAll(' ','-');const picture=document.createElement('div');picture.className='picture';article.append(picture);draw(base(picture,name));const info=document.createElement('div');info.className='example-notes';info.innerHTML=`<span class="family">${family}</span><h3>${sub}</h3><p>${desc}</p><dl><dt>Colours</dt><dd>${colors}</dd><dt>Motion</dt><dd>${motion}</dd></dl>`;article.append(info);grid.append(article);});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const f=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('.example').forEach(card=>card.hidden=f!=='All'&&card.dataset.family!==f);document.getElementById('count').textContent=document.querySelectorAll('.example:not([hidden])').length+' examples';}));
document.getElementById('texture-toggle').addEventListener('change',e=>document.body.classList.toggle('no-texture',!e.target.checked));
document.getElementById('shadow-toggle').addEventListener('change',e=>document.body.classList.toggle('no-shadow',!e.target.checked));
})();
